#https://docs.docker.com/compose/extends/
services:
  nginx:
    image: nginx:1.15-alpine
    depends_on:
      - sbaweb
    restart: unless-stopped
    volumes:
      - ./nginx/data/nginx:/etc/nginx/conf.d
      - ./nginx/data/certbot/conf:/etc/letsencrypt
      - ./nginx/data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
      - "44343:44343"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./nginx/data/certbot/conf:/etc/letsencrypt
      - ./nginx/data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  sbaweb:
    build: 
      context: .
      dockerfile: ./simplebibleapp/Dockerfile
    depends_on:
      - sbaredis
      - azurite
      - sbasilo
    ports:
      - '5001:8080'
    environment:
      - ConnectionStrings__Redis=sbaredis:6379
      - DataplanePath=/app/dataplane
      - ORLEANS_AZURE_STORAGE_CONNECTION_STRING=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;QueueEndpoint=http://azurite:10001/devstoreaccount1;TableEndpoint=http://azurite:10002/devstoreaccount1;
    volumes:
      - ~/.gemini:/root/.gemini
      - ./dataplane:/app/dataplane
      - ./dataprotection-keys:/root/.aspnet/DataProtection-Keys

  sbasilo:
    build: 
      context: .
      dockerfile: ./simplebibleapp.Silo/Dockerfile
    depends_on:
      - azurite
    environment:
      - ORLEANS_AZURE_STORAGE_CONNECTION_STRING=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;QueueEndpoint=http://azurite:10001/devstoreaccount1;TableEndpoint=http://azurite:10002/devstoreaccount1;
    volumes:
      - ~/.gemini:/root/.gemini

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    command: azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0 --skipApiVersionCheck
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - ./azurite-data:/data

  sbaredis:
    image: "redis:alpine"
    command: redis-server --appendonly yes
    ports:
      - '6379:6379'